spring:
  redis:
    port: 6379
    host: localhost
    password: 123456
  profiles:
    active: dev
server:
  port: 8081

# openSlide相关配置
open-slide:
  img-size: 256 # 切割的图片像素
  img-type: jpg # 切割的图片类型